apiVersion: v1
kind: Service
metadata:
  name: taskcafe-lb
  labels:
    app: taskcafe
spec:
  selector:
    app: taskcafe
  ports:
  - name: http
    port: 80
    targetPort: 3333
  type: LoadBalancer
