apiVersion: v1
data:
  taskcafe-config.toml: |
    [database]
    host = 'postgres-service'
    name = 'taskcafe'
    user = 'taskcafe'
    password = 'taskcafe_test'

    [job]
    broker = 'redis://redis-service:6379'
    store = 'redis://redis-service:6379'

    [message]
    queue = 'redis-service:6379'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: taskcafe-config